#!/bin/bash

# To update the version shipped in this quickstart, bump this variable:
#
install_version="2.7"

# Download and install Moodle

install_dir=${OPENSHIFT_BUILD_DEPENDENCIES_DIR}${install_version}

# Used in this script only
current_version_dir=${OPENSHIFT_DATA_DIR}current

#
# If Moodle is already installed in the current gear, there
# is nothing to build :-)
#
[ -d "${current_version_dir}" ] && exit 0

mkdir -p $install_dir

pushd ${install_dir} >/dev/null
curl -Ls http://download.moodle.org/stable27/moodle-2.7.tgz > moodle.tar.gz


# Install Moodle
#
tar --strip-components=1 -xzf moodle.tar.gz
rm -rf moodle.tar.gz
echo $install_version > ${OPENSHIFT_BUILD_DEPENDENCIES_DIR}.current_version

popd >/dev/null
