#!/bin/bash

# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

dest_dir=${OPENSHIFT_DATA_DIR}current

current_version=$(cat ${OPENSHIFT_BUILD_DEPENDENCIES_DIR}.current_version)
install_dir=${OPENSHIFT_BUILD_DEPENDENCIES_DIR}${current_version}

if [ ! -d "${dest_dir}" ]; then
  mkdir -p $dest_dir
  cp -rf ${install_dir}/* ${dest_dir}/
fi

if [ -d ${OPENSHIFT_REPO_DIR}php ]; then
  rm -rf ${OPENSHIFT_REPO_DIR}php
fi
ln -sf ${dest_dir} ${OPENSHIFT_REPO_DIR}php

set -e

if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
then
    echo 1>&2
    echo "Could not find mysql database.  Please run:" 1>&2
    echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.1" 1>&2
    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
    echo 1>&2
fi

if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
then
    exit 5
fi
# Confirm database exists, if not create it
if ! /usr/bin/mysql -u "$OPENSHIFT_MYSQL_DB_USERNAME" --password="$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" -P "$OPENSHIFT_MYSQL_DB_PORT" -e "select * from mdl_config;" moodle > /dev/null 2>&1
then
    echo "Creating database"
    php ${OPENSHIFT_REPO_DIR}php/admin/cli/install.php --lang=IT --wwwroot="http://"$OPENSHIFT_APP_DNS --dbhost=$OPENSHIFT_MYSQL_DB_HOST --dbuser=$OPENSHIFT_MYSQL_DB_USERNAME --dbpass=$OPENSHIFT_MYSQL_DB_PASSWORD --dbport=$OPENSHIFT_MYSQL_DB_PORT --adminpass=moodle --agree-license --non-interactive --shortname=Moodle --fullname="Moodle Openshift Install"
else
    echo "Database already configured. Scaling up"
    #creating moodledata directory (synched in the future)
    mkdir $OPENSHIFT_DATA_DIR/moodledata
    #creating config.php at runtime
    touch $OPENSHIFT_DATA_DIR/current/config.php
    cat <<EOF > $OPENSHIFT_DATA_DIR/current/config.php
cat <<EOF > config.php
<?php  // For scaling - Runtime generated
unset(\$CFG);
global \$CFG;
\$CFG = new stdClass();
\$CFG->dbtype    = 'mysqli';
\$CFG->dblibrary = 'native';
\$CFG->dbhost    = '$OPENSHIFT_MYSQL_DB_HOST';
\$CFG->dbname    = 'moodle';
\$CFG->dbuser    = '$OPENSHIFT_MYSQL_DB_USERNAME';
\$CFG->dbpass    = '$OPENSHIFT_MYSQL_DB_PASSWORD';
\$CFG->prefix    = 'mdl_';
\$CFG->dboptions = array (
  'dbpersist' => 0,
  'dbport' => '$OPENSHIFT_MYSQL_DB_PORT\',
  'dbsocket' => '',
);
\$CFG->wwwroot   = 'http://$OPENSHIFT_APP_DNS';
\$CFG->dataroot  = '${OPENSHIFT_DATA_DIR}moodledata';
\$CFG->admin     = 'admin';
\$CFG->directorypermissions = 02777;
require_once(dirname(__FILE__) . '/lib/setup.php');
EOF


fi
